Support for url encoded parameters and httpBody
tooploox/Networking-iOS pull request #3
Opened 2018-09-14 11:12 UTC by PChmiel

2018-09-14 13:46 UTC, Vyeczorny requested changes

2018-09-14 13:46 UTC, Vyeczorny commented on C0T0/Classes/ApiDataSource/URLRequestBuilder.swift
> +        if let urlParameters = request.urlParameters {
A bit more concise code for that:
```
let urlParametersString = urlParameters?.map { "\(key)=\(value)" }.joined(separator: "&") ?? ""
```

2018-09-14 13:46 UTC, Vyeczorny commented on C0T0/Classes/ApiDataSource/URLRequestBuilder.swift
> +        guard let  url = URL(string: host + request.endpoint + urlParametersString) else { return nil }
I think there is a small error. Current implementation adds `&` before every parameter, so before first parameter too. imo the sign which separates endpoint and parameters is `?`, not `&`.

2018-09-14 13:46 UTC, Vyeczorny commented on C0T0/Classes/Models/ApiRequest.swift
> +public typealias HTTPBody = [String: Any]
I think `HTTPBody` should be just `Data`

2018-09-14 13:46 UTC, Vyeczorny commented on C0T0/Classes/Models/ApiRequest.swift
> +        switch (lhs.urlParameters, rhs.urlParameters) {
Looks like nice code for separate comparing function ;)

2018-09-14 14:23 UTC, pstasiak commented on C0T0/Classes/ApiDataSource/URLRequestBuilder.swift
> +            for (key, value) in urlParameters {
Why not constructing url using `URLComponents.queryItems` + 'URLQueryItem'?

2018-09-17 09:28 UTC, pstasiak approved these changes

2018-09-17 10:28 UTC, Vyeczorny requested changes

2018-09-17 10:28 UTC, Vyeczorny commented on C0T0/Classes/ApiDataSource/URLRequestBuilder.swift
> +    private enum Constants {
I must admit I don't like this enum. Will we use `slashes` constant without scheme? If not, U don't see any advantages of keeping separate constants and I would leave just two constants: `http://` and `https://`.

2018-09-17 10:28 UTC, Vyeczorny commented on C0T0/Classes/ApiDataSource/URLRequestBuilder.swift
> +            host = host.replacingOccurrences(of:Constants.httpProtocol , with: "")
You can just make an assignment like: `self.host = host.replacingOccurrences(of:Constants.httpProtocol , with: "")`. I will allow you to remove two local variables and four lines of code :)

2018-09-17 10:28 UTC, Vyeczorny commented on C0T0/Classes/ApiDataSource/URLRequestBuilder.swift
> +            host = host.replacingOccurrences(of:Constants.httpProtocol , with: "")
Btw, you missed space after `:` :)

2018-09-17 10:28 UTC, Vyeczorny commented on C0T0/Classes/ApiDataSource/URLRequestBuilder.swift
> +        var components = URLComponents()
![image](https://user-images.githubusercontent.com/1502999/45618082-d528e580-ba74-11e8-8af0-9198da30d9a7.png)
As you can see on the screenshot, `URLComponents` can split address into scheme and host, so you don't need to do it manually, just pass whole `host` to it :)

2018-09-17 10:33 UTC, Vyeczorny approved these changes

2018-09-17 11:22 UTC, merged