Create README.md
tooploox/Networking-iOS pull request #6
Opened 2018-09-18 09:09 UTC by PChmiel

2018-09-18 09:51 UTC, skarol commented on README.md
> +        let apiRequest = ApiRequest(endpoint: "/endpoint",
we usually format like this:
```
ApiRequest(
    endpoint: "/endpoint",
    method: .GET, 
    urlParameters: ["sampleKey": "sampleValue"]
)
```

2018-09-18 09:51 UTC, skarol commented on README.md
> +        let apiRequest = ApiRequest(endpoint: "/users",
same

2018-09-18 10:51 UTC, Vyeczorny requested changes

2018-09-18 10:51 UTC, Vyeczorny commented on README.md
> +C0T0 - simply networking library for iOS based on NSURLSession
`simply` or `simple`? ;)

2018-09-18 10:51 UTC, Vyeczorny commented on README.md
> +Next create instance of `ApiService`
I thin k it should be comma after `Next` word

2018-09-18 10:51 UTC, Vyeczorny commented on README.md
> +Remember to retain the `apiService` object instead of creating local variable inside a function's scope, otherways your object may be released before the response will be received.
otherwise

2018-09-18 10:51 UTC, Vyeczorny commented on README.md
> +Here's an example of `requestRepositories(for ogranization)` function with setting repositories array for success or showing the error alert in case of failure. For parsing the results we're using `C
I think method name is `requestRepositories(for:)`, `organization` is just a parameter name and it doesn't count to method name

2018-09-18 10:51 UTC, Vyeczorny commented on README.md
> +Here's an example of `requestRepositories(for ogranization)` function with setting repositories array for success or showing the error alert in case of failure. For parsing the results we're using `C
`Result` word should be taken in backticks, since it is a type name.

2018-09-18 10:51 UTC, Vyeczorny commented on README.md
> +`ApiService` supports also downloading the content.
I would swap the order of words `also` and `supports`, imo "ApiService also supports downloading" sounds more natural.

2018-09-18 11:11 UTC, skarol commented on README.md
> +                             urlParameters: ["sampleKey": "sampleValue"])
endBracelet should be in new line

2018-09-18 11:11 UTC, skarol commented on README.md
> +                                           loggingEnabled: true)
endBracelet should be in new line

2018-09-18 11:11 UTC, skarol commented on README.md
> +                             headers: ["Content-Type": "application/json"])
endBracelet should be in new line

2018-09-18 11:11 UTC, skarol commented on README.md
> +                [...]
i would insert comment here. like: `// Your's code goes here`

2018-09-19 05:06 UTC, Vyeczorny approved these changes

2018-09-19 06:59 UTC, skarol approved these changes

2018-09-19 07:01 UTC, merged